// Generated by gencpp from file balboa_core/balboaMotorSpeeds.msg
// DO NOT EDIT!


#ifndef BALBOA_CORE_MESSAGE_BALBOAMOTORSPEEDS_H
#define BALBOA_CORE_MESSAGE_BALBOAMOTORSPEEDS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace balboa_core
{
template <class ContainerAllocator>
struct balboaMotorSpeeds_
{
  typedef balboaMotorSpeeds_<ContainerAllocator> Type;

  balboaMotorSpeeds_()
    : header()
    , left(0)
    , right(0)  {
    }
  balboaMotorSpeeds_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , left(0)
    , right(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _left_type;
  _left_type left;

   typedef int8_t _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> const> ConstPtr;

}; // struct balboaMotorSpeeds_

typedef ::balboa_core::balboaMotorSpeeds_<std::allocator<void> > balboaMotorSpeeds;

typedef boost::shared_ptr< ::balboa_core::balboaMotorSpeeds > balboaMotorSpeedsPtr;
typedef boost::shared_ptr< ::balboa_core::balboaMotorSpeeds const> balboaMotorSpeedsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::balboa_core::balboaMotorSpeeds_<ContainerAllocator1> & lhs, const ::balboa_core::balboaMotorSpeeds_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.left == rhs.left &&
    lhs.right == rhs.right;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::balboa_core::balboaMotorSpeeds_<ContainerAllocator1> & lhs, const ::balboa_core::balboaMotorSpeeds_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace balboa_core

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "81401375253b01074df288a02d8d49bf";
  }

  static const char* value(const ::balboa_core::balboaMotorSpeeds_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x81401375253b0107ULL;
  static const uint64_t static_value2 = 0x4df288a02d8d49bfULL;
};

template<class ContainerAllocator>
struct DataType< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "balboa_core/balboaMotorSpeeds";
  }

  static const char* value(const ::balboa_core::balboaMotorSpeeds_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"\n"
"int8 left\n"
"int8 right\n"
"\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::balboa_core::balboaMotorSpeeds_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct balboaMotorSpeeds_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::balboa_core::balboaMotorSpeeds_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::balboa_core::balboaMotorSpeeds_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    Printer<int8_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int8_t>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BALBOA_CORE_MESSAGE_BALBOAMOTORSPEEDS_H
